Django-1.4.3/projects/mysite/urls.py
from django.conf.urls.defaults import patterns, include, url
from mysite.views import *
from mysite.archive.views import *
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$',  login, {'template_name': 'tpl_login.html'}),
    (r'^accounts/logout/$', logout, {'next_page': '/'}),
    (r'^$', main_page),
    (r'^document/(\d{1,6})$', document_page),
    (r'^file/([A-Za-z\d]+)$', document_file),
#    (r'^ajax_filtered_fields/', include('ajax_filtered_fields.urls')),
#    ('^hello/$', hello),
#    ('^date/$', current_datetime),
#    (r'^date/offs/(\d{1,2})/$', hours_ahead),
#    (r'^books/$', book_list),
    #(r'^auth:([a-z0-9]+)/$', get_file),
    #(r'^getfile/$', get_file),
)
urlpatterns += staticfiles_urlpatterns()


#if settings.DEBUG:
#    urlpatterns += patterns('',
#        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + '/media'}),
#    )

Django-1.4.3/projects/mysite/archive/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields import IntegerField
from django.utils.translation import ugettext_lazy as _

class Divisions(models.Model):
    name = models.CharField(_('Division name'), max_length=255)
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = _('Division')
        verbose_name_plural = _('Divisions')

class DocumentType(models.Model):
    name = models.CharField(_('Document type name'), max_length=100)
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = _('Document type')
        verbose_name_plural = _('Document types')

class Documents(models.Model):
    PAPERSIZE = ((0, 'A0'), (1, 'A1'), (2, 'A2'), (3, 'A3'), (4, 'A4'), (5, 'A5'), (6, 'A6'),)
    WAGONUNITS = ((0, _('Other')), (1, _('Wheelpair')), (2, _('Axle box')), (3, _('Bogie')), (4, _('Auto coupling')),
                  (5, _('Brake')), (6, _('Wage body')), (7, _('Cadre')), (8, _('Attachments')), (8, _('Wagon')),
                  (9, _('Sling van')),)
    DOCSTATE = ((0, _('Valid')), (1, _('Changed')), (2, _('Canceled')))
    title = models.CharField(_('Document title'), max_length=255)
    page_cnt = models.PositiveIntegerField(_('Page count'))
    paper_size = models.IntegerField(_('Paper size'), choices=PAPERSIZE, default=4)
    archive_number = models.CharField(_('Archive number'),
        help_text=_('Type and number of document in archive'), max_length=100)
    document_number = models.CharField(_('Document number'),
        help_text=_('Document number based on company convention'), max_length=100)
    date_approved = models.DateField(_('Date of approval'))
    approver = models.CharField(_('Document approver'),
        help_text=_('Company (and post)'), max_length=255)
    date_archived = models.DateField(_('Added to archive'),
        help_text=_('Date, when the document was added to archive'), auto_now_add=True)
    date_start = models.DateField(_('Date of commissioning'))
    division = models.ManyToManyField(Divisions, verbose_name=_('Division name'),
        help_text=_('Name of division, where this document is to be used'))
    doc_type = models.ForeignKey(DocumentType, verbose_name=_('Document type'),
        help_text=_('Instruction, draft album etc'))
    state = models.IntegerField(_('Current state'), choices=DOCSTATE, default=0)
    canceled_by = models.ForeignKey('self', verbose_name=_('Related document'),
        help_text=_('Document which replaces or modifies this one'), null=True, blank=True)
    developer = models.CharField(_('Document developer'),
        help_text=_('Company (and department if any)'), max_length=255)
    related_unit = models.IntegerField(_('Related wagon unit'), choices=WAGONUNITS, default=0)
    note = models.TextField(_('Note'), max_length=2048, null=True, blank=True) #2Kb
    def __unicode__(self):
        return self.title + ' - ' + self.document_number
    class Meta:
        verbose_name = _('Document')
        verbose_name_plural = _('Documents')

class Files(models.Model):
    doc_num = models.ForeignKey(Documents, verbose_name=_('Related document'),
        help_text=_('Document, which this file is related to'))
    file_src = models.FileField(upload_to = 'filestorage', verbose_name=_('Upload file'))
    description = models.CharField(_('File description'), max_length=255, null=True, blank=True)
    access_level = models.PositiveIntegerField(_('Required access level'))
    class Meta:
        verbose_name = _('File')
        verbose_name_plural = _('Files')
    def __unicode__(self):
        return str(self.doc_num.id) + ' - ' + self.file_src.url

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)

    file_access_level = models.PositiveIntegerField(_('Level of file access rights'))
    divisions_access = models.ManyToManyField(Divisions, verbose_name=_('Available divisions'),
        help_text=_('Divisions, which can be accessed by current profile'), null=True, blank=True)
    def __unicode__(self):
        return self.user.username
    class Meta:
        verbose_name = _('User profile')
        verbose_name_plural = _('User profiles')

class FileLinks(models.Model):
    user = models.ForeignKey(User)
    expires = models.DateTimeField()
    secret_link = models.CharField(max_length=11)
    file = models.ForeignKey(Files)

#class NaturalNumbers(models.IntegerField):
#    "dfnbdnbdgndx"
#    def __init__(self, verbose_name=None, min_value=None, max_value=None, **kwargs):
#        IntegerField.__init__(self, verbose_name, **kwargs)
#        self.min_value = min_value
#        self.max_value = max_value
#    def formfield(self, **kwargs):
#        return models.IntegerField.formfield(self,  min_value=self.min_value, max_value=self.max_value, **kwargs)
#    def get_internal_type(self):
#        return "IntegerField"
#
#class MMIntegerField(models.IntegerField):
#    "Min Max Integer Field - use in place of models.IntegerField"
#    def __init__(self, verbose_name=None, min_value=None, max_value=None, **kwargs):
#        IntegerField.__init__(self, verbose_name, **kwargs)
#        self.min_value = min_value
#        self.max_value = max_value
#    def formfield(self, **kwargs):
#        return models.IntegerField.formfield(self,  min_value=self.min_value, max_value=self.max_value, **kwargs)
#    def get_internal_type(self):
#        return "IntegerField"
#
#class FileLinks2(models.Model):
#    xxx = NaturalNumbers(min_value=1,max_value=5)

Django-1.4.3/projects/mysite/templates/tpl_base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
{% load i18n %}
<html>
<head>
    {% block headdata %}{% endblock %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="icon" href="{{ STATIC_URL }}favicon.png" type="ico">
    <title>{% block title %}{% endblock %} {{ project_name }}</title>
    <link href="{{ STATIC_URL }}base.css" rel="stylesheet" type="text/css">
</head>

<body>

<div class="pagestyle">
<table width="100%"><tr>
<td><img src="{{ STATIC_URL }}pic_rzd_logo.gif" alt=""><img src="{{ STATIC_URL }}pic_rzd_text.gif" alt=""></td>
<td align="right"><a href="/"><img src="{{ STATIC_URL }}header.png" alt="" border="0"></a></td>
</tr></table>
<table width="100%">
<tr>
<td>{% block profileinfo %}{% endblock %}</td>
<td align="right">{% trans 'User name' %}: <b>{% if user.last_name %}{{ user.first_name }} {{ user.last_name }}{% else %}{{ user.username }}{% endif %}</b>, <a href="/accounts/logout/">{% trans 'Logout' %}</a></td>
</tr>
</table>

<div class="mainblock">
{% block content %}{% endblock %}
<p style="font-size: 10pt; margin: 0px" align="right"><i>Легенда:</i> <span class="css_docmodified">документ изменён</span>, <span class="css_doccanceled">действие прекращено</span></p>
</div>
<h6 align="center"><a href="mailto:aurpkbcv@yandex.ru">ПКБ ЦВ ОАО "РЖД"</a>, {{ product_year }}</h6>
</div>
</body>
</html>

Django-1.4.3/projects/mysite/templates/tpl_document.html
{% extends "tpl_base.html" %}
{% block title %}Обзор документа {% if not access_error %}'{{ doc.document_number }}' {% endif %}|{% endblock %}
{% block profileinfo %}
<table cellspacing="4">
    <tr align="center">
        <td title="Доступ к документам не выше этого уровня"><i>Уровень доступа</i></td>
    </tr>
    <tr align="center">
        <td><b>{{ file_acc_lvl }}</b></td>
    </tr>
</table>
{% endblock %}
{% block content %}
{% if not access_error %}

<table cellpadding="4">
<tr>
    <td colspan="6"><i>Название:</i> <b>{{ doc.title }}</b></td>
</tr>
<tr>
    <td align="right"><i>Номер документа:</i></td><td>{{ doc.document_number }}</td>
    <td align="right"><i>Архивный номер:</i></td><td>{{ doc.archive_number }}</td>
    <td align="right"><i>Введён в действие:</i></td><td>{{ doc.date_start }}</td>
</tr>
<tr>
    <td align="right"><i>Число страниц:</i></td><td>{{ doc.page_cnt }}</td>
    <td align="right"><i>Формат бумаги:</i></td><td>{{ doc.get_paper_size_display }}</td>
    <td align="right"><i>Тип:</i></td><td>{{ doc.doc_type }}</td>
</tr>
<tr>
    <td align="right"><i>Разработчик:</i></td><td>{{ doc.developer }}</td>
    <td align="right"><i>Утверждён:</i></td><td colspan="2">{{ doc.approver }} ({{ doc.date_approved }})</td>
</tr>
<tr>
    <td align="right"><i>Узел вагона:</i></td><td>{{ doc.get_related_unit_display }}</td>
    <td align="right"><i>Подразделения:</i></td><td colspan="3">{% for div in doc.division.all %}{{ div }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
</tr>
<tr>
    <td align="right"><i>Добавлен в архив:</i></td><td>{{ doc.date_archived }}</td>
    <td align="right"><i>Состояние:</i></td>
    <td><span class="{% if doc.state == 2 %}css_doccanceled{% else %}{% if doc.state == 1 %}css_docmodified{% else %}css_docnormal{% endif %}{% endif %}">
        {{ doc.get_state_display }}
    </span></td>
    {% if doc.state > 0 %}{% if doc.canceled_by.document_number %}
    <td><div class="css_pressblock" style="margin: 0px" onclick = "window.location.href = '/document/{{ doc.canceled_by.id }}'">{{ doc.canceled_by.document_number }}</div></td>
    {% endif %}{% endif %}
</tr>
{% if doc.note %}<tr>
    <td align="right"><i>Примечание:</i></td><td colspan="5">{{ doc.note }}</td>
</tr>{% endif %}
</table>

{% if files %}
<br>
<div class="css_container"><i>Доступные файлы:</i>
    {% for file in files %}
    <div class="css_pressblock" onclick = "window.location.href = '/file/{{ file.1 }}'">
        {{ file.2 }}{% if file.0.description %} - <i>{{ file.0.description }}</i>{% endif %}
    </div>
    {% endfor %}
</div><br>
{% endif %}
{% else %}
<div class="css_nopressblock">
    <p align="center"><span style="color: #e8382a; font-weight: bold;">Ошибка доступа</span>: документ не существует или у вас не достаточно прав для его просмотра</p>
</div><br>
{% endif %}
{% if has_back_button %}
    <a href="javascript:history.back()" style="float: left; margin: 0px 4px"><< Назад</a>
{% endif %}
{% endblock %}

Django-1.4.3/projects/mysite/templates/tpl_inc_paginator.html
{% if docs_page.paginator.num_pages > 1 %}
<p align="center" style="font-size: 10pt">
{% if docs_page.has_previous %}
    <a href="?page_num=1&{{ get_form_filter }}"><<</a>
    <a href="?page_num={{ docs_page.previous_page_number }}&{{ get_form_filter }}">Назад</a>
{% endif %}
    <span class="current">{{ docs_page.number }} из {{ docs_page.paginator.num_pages }}</span>
{% if docs_page.has_next %}
    <a href="?page_num={{ docs_page.next_page_number }}&{{ get_form_filter }}">Вперёд</a>
    <a href="?page_num={{ docs_page.paginator.num_pages }}&{{ get_form_filter }}">>></a>
{% endif %}
</p>
{% endif %}

Django-1.4.3/projects/mysite/templates/tpl_login.html
{% extends "admin/login.html" %}
{% load i18n %}
{% block title %}
    {% trans 'Enter site' %} | {{ project_name }}
{% endblock %}
{% block extrahead %}<link rel="icon" href="/static/pictures/favicon.png" type="ico">{% endblock %}
{% block branding %}
    <h1 id="site-name">{% trans 'Enter site' %}</h1>
{% endblock %}
{% block breadcrumbs %}
    {% if form.non_field_errors %}
        <p class="errornote">{% trans 'Sorry, login or password is incorrect' %}</p>
    {% endif %}
{% endblock %}